export const CURRENCIES = ['UAH', 'USD', 'EUR'];
export const ADDRESS_PARTS=
    ['COUNTRY_SENDER',
        'REGION_SENDER',
        'CITY_SENDER',
        'POST_DEPARTMENT_NUMBER_SENDER',
        'COUNTRY_RECIPIENT',
        'REGION_RECIPIENT',
        'CITY_RECIPIENT',
        'POST_DEPARTMENT_NUMBER_RECIPIENT',
        'POST_DEPARTMENT_TYPE_RECIPIENT',
        'STREET_RECIPIENT',
        'BUILDING_RECIPIENT'];
export const PAYMENT_TYPE = ['COD', 'PREPAYMENT']

export const DELIVERY_SERVICE_TYPE = ['NOVA_POST', 'NONE']